micronaut:
    application:
        name: person-crud
    server:
        port: 8085

dataSource:
    url: jdbc:h2:mem:micronaut;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver