# ToDo: research how to create multiple `data sources`

micronaut:
    application:
        name: person-crud
    server:
        port: 8086
        cors:
            enabled: true
    io:
        watch:
            paths: src/main
            restart: false
    security:
        enabled: true
        endpoints:
            login:
                enabled: false
            oauth:
                enabled: false
        token:
            jwt:
              enabled: true
              signatures:
                jwks:
                  {localhost}:
                    url: "https://localhost/.well-known/jwks.json"
dataSource:
    pooled: true
    dbCreate: update
    url: jdbc:mysql://localhost:3306/micronaut?useSSL=false
    username: micronaut
    password: 12qwaszx!

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

